# Generated by Django 4.2.5 on 2025-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sale', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to='media/slider')),
            ],
        ),
    ]
