# Generated by Django 4.2.5 on 2025-08-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='name',
            new_name='phonename',
        ),
    ]
