# Generated by Django 4.2.5 on 2025-11-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_1',
        ),
    ]
