# Generated by Django 4.2.5 on 2025-11-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_product_product_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_1',
            name='image',
            field=models.ImageField(default=1, upload_to='media/Images'),
            preserve_default=False,
        ),
    ]
